<form id="frmAddReading">
    <table>
        <tr>
            <td><label for="status">Status: </label></td>
                <span>Read:</span>
                <input dojoType="dijit.form.RadioButton" type="radio" name="status" value="0">
                <label>Reading:</label>
                <input dojoType="dijit.form.RadioButton" type="radio" name="status" value="1" checked="checked"/>
                <label>To Read:</label>
                <input dojoType="dijit.form.RadioButton" type="radio" name="status" value="2"/>
            </td>
        </tr>
        <tr>
            <td><label for="name">ISBN: </label></td>
            <td><input dojoType="dijit.form.TextBox" type="text" name="isbn" style="width:300px;" value="" /></td>
        </tr>
        <tr>
            <td><label for="name">Title: </label></td>
            <td><input dojoType="dijit.form.TextBox" type="text" name="title" style="width:300px;" value="" /></td>
        </tr>
        <tr>
            <td><label for="name">Author: </label></td>
            <td><input dojoType="dijit.form.TextBox" type="text" name="author" style="width:300px;" value="" /></td>
        </tr>
        <tr>
            <td><label for="name">Book year: </label></td>
            <td><input dojoType="dijit.form.TextBox" type="text" name="bookyear" style="width:300px;" value="" /></td>
        </tr>
        <tr>
            <td><label for="body">Why: </label></td>
            <td>
                <textarea name="why" dojoType="dijit.form.SimpleTextarea" style="width:300px;height:200px"></textarea>
            </td>
        </tr>
        <tr>
            <td align="right" colspan="2">
                <button dojoType="dijit.form.Button" onClick='Books.saveReading()'>Save</button>
            </td>
        </tr>
    </table>
</form>