<table jsID='books.toread' dojoType="dojox.grid.DataGrid" width="250px"
    store="strBooks.toread"
    clientSort="true"
    onRowDblClick ="Books.bookGridDblClick"
    style="width: 250px; height: 250px;"
    >
    <thead>
        <tr>
            <th width="20%" field="title">title</th>
            <th width="20%" field="author">author</th>
            <th width="10%" field="bookyear">bookyear</th>
            <th width="50%" field="why">why</th>
        </tr>
        
    </thead>
</table>
