<div dojoType="dijit.layout.ContentPane" title="First Tab" style="width:400px;">
    <p>This is the personal home page of <b>Gonzalo Ayuso</b>.</p>
    <p>
        This project pretends to be my personal project's portfolio and <br/>
        a container of prototypes with technologies such as Dojo and Zend Framework:
    </p>
    <table width="100%" cellpadding="2" cellspacing="2">
        <tr>
            <td width="100%" align="center">
            <a href="http://dojotoolkit.org/" target="_blank"><img src="<?= Zend_Registry::get('config')->document_root ?>/images/dojo.logo.png" height="25" width="39" border="0" alt="zen framework"/></a>
            <a href="http://framework.zend.com/" target="_blank"><img src="<?= Zend_Registry::get('config')->document_root ?>/images/zf.logo.png" height="25" width="38" border="0" alt="zen framework"/></a>
            </td>
        </tr>
    </table>
    <p>
    The Applications I create are only excuses to learn new tools and get new skills.
    I my daily work I use to work with a custom PHP frameworks and JQuery.
    Because of that I've created this personal project,
    to use other technologies different than the tools I use to work with.
    </p>

</div>