<form id='contactFrm'>
<p>Feel free to send me a message </p>
<table cellpadding="0" cellspacing="0">
    <tr>
        <td>
            Email:
        </td>
        <td>
            <input
                name="email"
                dojoType="dijit.form.ValidationTextBox"
                regExpGen="dojox.regexp.emailAddress"
                trim="true"
                required="true"
                invalidMessage="Invalid Email Address."
                type="text" style="width:300px;" />
        </td>
    </tr>
    <tr>
        <td>
            Subject:
        </td>
        <td>
            <input name="subject" required="true" dojoType="dijit.form.ValidationTextBox" type="text" style="width:300px;" />
        </td>
    </tr>
    <tr>
        <td>
            Body:
        </td>
        <td>
            <textarea name="body" required="true" dojoType="dijit.form.SimpleTextarea" style="width:300px;height:200px"></textarea>
        </td>
    </tr>
    <tr>
        <td colspan="2" align="right">
            <button name='body' dojoType="dijit.form.Button" onClick='Main.sendEmail()'>Send</button>
        </td>
    </tr>
</table>
</form>