<div dojoType="dijit.layout.BorderContainer" design="sidebar" gutters="true" style="height: 450px; width: 650px;">
    <div dojoType="dijit.layout.ContentPane" region="top" style="height: 80px" align="right">
        <?= $this->partial('info/cvheader.phtml')?>
	</div>
	<div dojoType="dijit.layout.ContentPane" region="center">
<ul>
<li>
Strong experience with <b>PHP</b> and <b>Python</b> more than 9 years.
</li>
<li>
Strong experience in web performance optimization. (Frontend and Backend)
</li>
<li>
Web server administration (<b>apache</b> and <b>lighttp</b>).
</li>
<li>
Experience Web Frontend technologies (<b>JQuery</b>, <b>Dojo</b>)
</li>
<li>
Experience Database administration (<b>Oracle</b>, <b>Postgresql</b> and <b>Mysql</b>)<br/> and data migration between them
</li>
<li>
Experinece in <b>Linux</b> administration.
</li>
<li>
Experience in agile team managementent (<b>SCRUM</b>)
</li>
<li>
Experience with Version Control System (<b>Git</b> and <b>Mercurial</b>)
</li>
<li>
Knowledge of Java and J2EE arquitectures.
</li>
</ul>
<p>
<b>Industrial Technnical Engineer </b>
Universidad del País Vasco (1995 – 1999)<br/>
End of degree project in Technological Educational Institute of Kavala. Greece (1999)
</p>
<p>
For a detailed C.V contact with me at: gonzalo123@gmail.com
</p>


	</div>
</div>



