<form id='form.notes.find'>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center">
            <input dojoType="dijit.form.TextBox" type="text" name="key" style="width:300px;" value="" />
        </td>
    </tr>
    <tr>
        <td align="right">
            <button dojoType="dijit.form.Button" onClick='Notes.find()'>Find</button>
        </td>
    </tr>
</table>
</font>