<div dojoType="dijit.layout.BorderContainer" design="headline" 
    splitter='true' gutters='true' style="width: 100%; height: 100%; border: solid 0px;">
    <div dojoType="dijit.layout.ContentPane" region="top" style="height: 80px;">
        <?= $this->partial('notes/header.phtml') ?>
    </div>
    <div dojoType="dijit.layout.ContentPane" region="center">
        <div dojoType="dijit.layout.BorderContainer" design="sidebar" gutters="false" persist="true" 
            style="height: 100%; width: 350px; border: solid 0px;">
            <div dojoType="dijit.layout.ContentPane" region="left">
                <button dojoType="dijit.form.Button" onClick='Notes.addNoteDialog()'>Add</button>
            </div>
		    <div dojoType="dijit.layout.ContentPane" region="top">
                <?= $this->partial('notes/find.phtml') ?>
            </div>
            <div dojoType="dijit.layout.ContentPane" region="center">
                <?= $this->partial('notes/grid.phtml') ?>
            </div>
            
        </div>
    </div>
</div>