<form id="notes.formNote_<?= $this->id ?>">
<input type="hidden" name="id" style="width:300px;" value="<?= $this->id ?>" />
    <table border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td><label for="name">Title: </label></td>
            <td><input dojoType="dijit.form.TextBox" type="text" name="title" style="width:300px;" value="<?= $this->title ?>" /></td>
        </tr>
        <tr>
            <td><label for="body">Text: </label></td>
            <td>
                <textarea name="body" dojoType="dijit.form.SimpleTextarea" style="width:300px;height:200px"><?= $this->body ?></textarea>
            </td>
        </tr>
        <tr>
            <td align="left">
                <button dojoType="dijit.form.Button" onClick='Notes.deleteDialog(<?= $this->id ?>)'>Delete</button>
            </td>
            <td align="right">
                <button dojoType="dijit.form.Button" onClick='Notes.edit(<?= $this->id ?>)'>Edit</button>
            </td>
        </tr>
    </table>
</form>