<form id="frmEditPlace">
<input type="hidden" name="id" style="width:150px;" value="<?= $this->data->id?>" />
    <table border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td><label for="name">Title: </label></td>
            <td><input dojoType="dijit.form.TextBox" type="text" name="title" style="width:150px;" value="<?= $this->data->title?>" /></td>
        </tr>
        <tr>
            <td><label for="body">Text: </label></td>
            <td>
                <textarea name="body" dojoType="dijit.form.SimpleTextarea" style="width:150px;height:100px"><?= $this->data->body?></textarea>
            </td>
        </tr>
        <tr>
            <td align="right" colspan="2">
                <button dojoType="dijit.form.Button" onClick='Places.editPlace()'>Save</button>
            </td>
        </tr>
    </table>
</form>