DROP TABLE IF EXISTS "tblFeatureList";
CREATE TABLE "tblFeatureList" ("id_productBacklog" INTEGER, "id" INTEGER PRIMARY KEY  NOT NULL , "type" INTEGER, "owner" VARCHAR, "description" VARCHAR, "estimated_hours" INTEGER, "estimated_date" DATETIME, "sprin_id" INTEGER);
DROP TABLE IF EXISTS "tblProductBacklog";
CREATE TABLE "tblProductBacklog" ("id" INTEGER PRIMARY KEY  NOT NULL , "name" VARCHAR, "description" VARCHAR, "date" DATETIME, "owner" VARCHAR);
INSERT INTO "tblProductBacklog" VALUES(1,'','','','');
INSERT INTO "tblProductBacklog" VALUES(2,'','','','');
DROP TABLE IF EXISTS "tblSprin";
CREATE TABLE "tblSprin" ("id" INTEGER PRIMARY KEY  NOT NULL ,"status" INTEGER,"description" VARCHAR,"id_productBacklog" INTEGER);
INSERT INTO "tblSprin" VALUES(1,'done','sdad','undefined');
INSERT INTO "tblSprin" VALUES(2,1,'','undefined');
DROP TABLE IF EXISTS "tblUsers";
CREATE TABLE "tblUsers" ("userid" VARCHAR PRIMARY KEY  NOT NULL , "name" VARCHAR, "surname" VARCHAR, "email" VARCHAR);
DROP TABLE IF EXISTS "tblbooks";
CREATE TABLE "tblbooks" ("id" INTEGER PRIMARY KEY  NOT NULL ,"title" VARCHAR,"author" VARCHAR,"bookyear" INTEGER,"readdate" DATETIME,"status" INTEGER,"why" VARCHAR,"valoration" VARCHAR,"stars" INTEGER, "asin" INTEGER);
INSERT INTO "tblbooks" VALUES(1,'Dojo. the definitive guide','Mattlhew A.Russell',2008,'',1,'','','',9780596516482);
INSERT INTO "tblbooks" VALUES(2,'Asterisk. The future of telephony','Jim Van Meggelen',2008,NULL,1,'I want to learn about Asterisk and open source PBX',NULL,NULL,NULL);
INSERT INTO "tblbooks" VALUES(3,'x','x','',NULL,1,'',NULL,NULL,NULL);
