<p>
<a href="#" onClick="Apps.startAppInTab('places', 'Places')">Places</a> is an aplication to mark places in google maps. 
</p>

<p>
I develop this aplication because I wanted to learn the extremely easy to use google maps API.
</p>

<p>
<h3>Todo:</h3>
<ul>
    <li>Eliminate Add button and allow to use the main map to insert the new places. Only addminstrator can add places, so i need to add and remove the 'on click' lisener of the map depending on the login session.</li>
    <li>Scale is a problem here too. Hundreds ok GMarks will cause a serious performance problems.</li>
</ul>
</p>