<p>
<a href="#" onClick="Apps.startAppInTab('notes', 'Notes')">Notes</a> is my first dojo application.
Is a really simple application to create mental notes or things that I have learn. Becouse as the application says '<i>You learn something new every day and you want to remember</i>'
</p>

<p>
<h3>Todo:</h3>
<ul>
    <li>Use the Implementation of Zend of <a href="http://framework.zend.com/manual/en/zend.search.lucene.html" target="_blank">Lucene</a> or <a href="http://www.sphinxsearch.com/" target="_blank">Sphinx</a> instead of database select into the search engine</li>
</ul>
</p>