<b>You are free:</b><br/>
<ul>
    <li><b>to Share</b> — to copy, distribute and transmit the work </li>
    <li><b>to Remix</b> — to adapt the work</li>
</ul>

<b>Under the following conditions:</b><br/>

<ul>
    <li><b>Attribution</b>. You must attribute the work in the manner specified by the author or licensor (but not in any way that suggests that they endorse you or your use of the work).</li>
    <li><b>Share Alike</b>. If you alter, transform, or build upon this work, you may distribute the resulting work only under the same, similar or a compatible license.</li>
    <li>For any reuse or distribution, you must make clear to others the license terms of this work. The best way to do this is with a link to this web page.</li>
    <li>Any of the above conditions can be waived if you get permission from the copyright holder.</li>
    <li>Nothing in this license impairs or restricts the author's moral rights.</li>
</ul>
<p>Source code available on: <a target="_blank" href="http://github.com/gonzalo123/gam/">github</a></p>
<div align="right">
<a rel="license" target="_blank" href="http://creativecommons.org/licenses/by-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/80x15.png" title="Gonzalo Ayuso. Some rights reserved."/></a>
</div>

