<div dojoType="dijit.layout.BorderContainer" gutters='true' design="headline" style="width: 100%; height: 100%; border: solid 0px;">
    <div dojoType='dijit.layout.ContentPane' region="center">
        <?= $this->partial('info/about.phtml')?>
    </div>
    <div dojoType='dijit.layout.ContentPane' region="right" style="width:300px">
        <?= $this->partial('info/apps.phtml')?>
    </div>
    <div dojoType='dijit.layout.ContentPane' region="left" style="width:300px">
        <?= $this->partial('info/feeds.phtml')?>
    </div>
    <div dojoType='dijit.layout.ContentPane' region="top" style="height:90px" align="right">
        <?= $this->partial('info/cvheader.phtml')?>
    </div>
</div>